### ISSUE TITLE
Mimir sometimes breaks spreadsheet mode

### ISSUE THREAD

**Issue by thomaseslowe** [VizierDB/vizier-scala#249]
1st off: It's really helpful

1st issue: It only allows me to see the number of rows that fits on my screen (maybe brower issue? (I'm using chrome on ubuntu))

2nd issue: if the 1st pixel of the last column fits in my browser, it will display off page. I can click on it, and it will shift to the right so I can see it, but there's no horizontal scroll bar so i can adjust otherwise.

3rd issue: if the dataset begins to get big, like say, more than a few hundred thousands of rows, it screams uncle and fails to load after about 60 seconds.

It would be really awesome if I could scroll down and/or enter a row # so that it would load the data from that section of the table. Something so that I can see snapshots of the data.........

**Comment by okennedy** [comment]
Is this Vizier 1.x (brown header bar, lots of rounded corners) or vizier 2.x (blue header bar, pointy corners)?

**Comment by thomaseslowe** [comment]
Vizier 2.x, got latest about 10 days ago

**Comment by okennedy** [comment]
On the 1st issue: Could you clarify what you mean by this?  e.g., It shows the first n rows, but then you get spinnies for the rest when you scroll?

On the 2nd issue... thanks. That should be fixable.  You should be able to shift-scroll to go left-right in the meantime.

On the 3rd issue: Where is the data coming from: a series of queries, or loaded straight from a file?

**Comment by thomaseslowe** [comment]
1st issue: no spinnies, i can't scroll downward or otherwise see any rows beyond what i can see in my screen. As always, could be user error here.......

2nd issue: awesome

3rd issue: direct from parquet file

**Comment by okennedy** [comment]
Re 1: Any chance you could take a screen recording of the effect?

**Comment by okennedy** [comment]
I think I've hacked in a temporary fix at the head of the 2.0 branch.  The problem appears to be related to Mimir.  I'll keep the ticket open until I can confirm that it's resolved, and push a corresponding fix to Mimir.

**Comment by okennedy** [comment]
This is now "fixed" by essentially disabling Mimir.  I wish there were a cleaner way, but the problem is basically that Mimir only supports a *subset* of spark's grammar.  As of right now, we don't have a particularly good fall-back when Mimir fails to rewrite a query... everything breaks.  

@lordpretzel @mrb24 : My vote is to keep Mimir disabled behind a feature flag for 2.0.  Mimir would still be present, with caveat annotations still being injected as appropriate; but we just wouldn't rewrite queries to produce caveat annotations unless the feature flag is enabled.  

For 2.1 or 2.2, we can update Mimir to fail more gracefully when it encounters unsupported features, or otherwise fails to rewrite a query, and then move to Mimir enabled by default.
